services:
  asr2api:
    container_name: asr2api
    image: ghcr.nju.edu.cn/aahl/qwen-asr2api:main
    ports:
      - 8820:80
    environment:
      #API_KEY: sk-your-dummy-key # The key for this API service, NOT for Qwen
      TZ: ${TZ:-Asia/Shanghai}
    restart: unless-stopped
